<?php

declare(strict_types=1);

namespace Tests\Unit\Models;

use App\Models\Brand;
use App\Models\Product;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Testing\WithFaker;
use PHPUnit\Framework\Attributes\CoversClass;
use Tests\TestCase;

/**
 * Unit tests for the Brand model.
 *
 * @internal
 */
#[CoversClass(Brand::class)]
final class BrandTest extends TestCase
{
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp();
        $this->faker = $this->faker();
    }

    protected function tearDown(): void
    {
        parent::tearDown();
    }

    /**
     * Test that products relation is a HasMany instance.
     */
    public function testProductsRelation(): void
    {
        $brand = new Brand();

        $relation = $brand->products();

        self::assertInstanceOf(HasMany::class, $relation);
        self::assertSame(Product::class, $relation->getRelated()::class);
    }

    /**
     * Test scopeActive adds where clause for is_active.
     */
    public function testScopeActive(): void
    {
        $query = Brand::query()->active();

        self::assertSame('select * from "brands" where "is_active" = ? and "brands"."deleted_at" is null', $query->toSql());
        self::assertSame([true], $query->getBindings());
    }

    /**
     * Test scopeSearch adds where like clause for name.
     */
    public function testScopeSearch(): void
    {
        $query = Brand::query()->search('test');

        self::assertSame('select * from "brands" where "name" like ? and "brands"."deleted_at" is null', $query->toSql());
        self::assertSame(['%test%'], $query->getBindings());
    }

    /**
     * Test that slug is auto-generated on creating if empty.
     */
    public function testSlugAutoGeneratedOnCreating(): void
    {
        $brand = new Brand(['name' => 'Test Brand']);
        $brand->save();

        self::assertSame('test-brand', $brand->slug);
        $brand->delete(); // cleanup
    }

    /**
     * Test that slug is auto-generated on updating if name changed and slug empty.
     */
    public function testSlugAutoGeneratedOnUpdating(): void
    {
        $brand = new Brand(['name' => 'Old Name', 'slug' => 'old-slug']);
        $brand->save();

        $brand->name = 'New Name';
        $brand->slug = null;
        $brand->save();

        self::assertSame('new-name', $brand->slug);
        $brand->delete();
    }

    /**
     * Test getRules returns the validation rules.
     */
    public function testGetRules(): void
    {
        $brand = new Brand();
        $rules = $brand->getRules();

        self::assertIsArray($rules);
        self::assertArrayHasKey('name', $rules);
        self::assertArrayHasKey('slug', $rules);
        self::assertArrayHasKey('is_active', $rules);
    }
}
